In [164]:
import pandas as pd  
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [165]:
df = pd.read_csv(r"D:\Projects\ML projects\Churn prediction\data\churn_data.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [167]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [168]:
df.drop('customerID', axis=1, inplace=True)
df.drop('gender', axis=1, inplace=True)
df.drop('PhoneService', axis=1, inplace=True)

In [169]:
df

,SeniorCitizen,Partner,Dependents,tenure,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Yes,No,1,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,0,No,No,34,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,0,No,No,2,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,0,No,No,45,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,0,No,No,2,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,Yes,Yes,24,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,0,Yes,Yes,72,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,0,Yes,Yes,11,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,1,Yes,No,4,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,0,No,No,66,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [170]:
#change total charges to numeric
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [171]:
df.isnull().sum()

SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [172]:
# handle missing values
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

C:\Users\unick\AppData\Local\Temp\ipykernel_9904\959162640.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

In [173]:
service_cols = ['MultipleLines','OnlineSecurity','OnlineBackup',
        'DeviceProtection','TechSupport','StreamingTV','StreamingMovies',"Contract"]
for i in service_cols:
    col = df[i].value_counts()
    print(i , col )

MultipleLines MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64
OnlineSecurity OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64
OnlineBackup OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64
DeviceProtection DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64
TechSupport TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64
StreamingTV StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64
StreamingMovies StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64
Contract Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [174]:
df.replace('No internet service', 'No', inplace=True)
df.replace('No phone service', 'No', inplace=True)

In [175]:
def Feature_Engineering(df) :
    service_cols = ['MultipleLines','OnlineSecurity','OnlineBackup',
        'DeviceProtection','TechSupport','StreamingTV','StreamingMovies'
    ]
    #number of services each costomer used
    df['NumServices']= df[service_cols].replace({'Yes':1, 'No':0}).sum(axis=1)
    # Avg monthly charge
    df['AvgMonthlyCharge'] = df['TotalCharges'] / (df['tenure'] + 1)

    return df

In [176]:
Feature_Engineering(df)

C:\Users\unick\AppData\Local\Temp\ipykernel_9904\1788085100.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['NumServices']= df[service_cols].replace({'Yes':1, 'No':0}).sum(axis=1)

,SeniorCitizen,Partner,Dependents,tenure,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,NumServices,AvgMonthlyCharge
0,0,Yes,No,1,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,14.925000
1,0,No,No,34,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,2,53.985714
2,0,No,No,2,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,2,36.050000
3,0,No,No,45,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,3,40.016304
4,0,No,No,2,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,50.550000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,Yes,Yes,24,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,6,79.620000
7039,0,Yes,Yes,72,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,5,100.861644
7040,0,Yes,Yes,11,No,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,1,28.870833
7041,1,Yes,No,4,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1,61.320000
7042,0,No,No,66,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,5,102.156716

In [177]:
df.head()

,SeniorCitizen,Partner,Dependents,tenure,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,NumServices,AvgMonthlyCharge
0,0,Yes,No,1,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,14.925000
1,0,No,No,34,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,2,53.985714
2,0,No,No,2,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,2,36.050000
3,0,No,No,45,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,3,40.016304
4,0,No,No,2,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,50.550000

In [186]:
cat_cols = ['Contract','PaymentMethod','InternetService']
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [187]:
df

,SeniorCitizen,Partner,Dependents,tenure,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,...,Churn,NumServices,AvgMonthlyCharge,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,InternetService_Fiber optic,InternetService_No
0,0,Yes,No,1,No,No,Yes,No,No,No,...,No,1,14.925000,False,False,False,True,False,False,False
1,0,No,No,34,No,Yes,No,Yes,No,No,...,No,2,53.985714,True,False,False,False,True,False,False
2,0,No,No,2,No,Yes,Yes,No,No,No,...,Yes,2,36.050000,False,False,False,False,True,False,False
3,0,No,No,45,No,Yes,No,Yes,Yes,No,...,No,3,40.016304,True,False,False,False,False,False,False
4,0,No,No,2,No,No,No,No,No,No,...,Yes,0,50.550000,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,Yes,Yes,24,Yes,Yes,No,Yes,Yes,Yes,...,No,6,79.620000,True,False,False,False,True,False,False
7039,0,Yes,Yes,72,Yes,No,Yes,Yes,No,Yes,...,No,5,100.861644,True,False,True,False,False,True,False
7040,0,Yes,Yes,11,No,Yes,No,No,No,No,...,No,1,28.870833,False,False,False,True,False,False,False
7041,1,Yes,No,4,Yes,No,No,No,No,No,...,Yes,1,61.320000,False,False,False,False,True,True,False
7042,0,No,No,66,No,Yes,No,Yes,Yes,Yes,...,No,5,102.156716,False,True,False,False,False,True,False

In [125]:
binary_cols = ["StreamingMovies","StreamingTV","TechSupport","DeviceProtection","OnlineBackup","OnlineSecurity","MultipleLines",'Partner','Dependents','PaperlessBilling','Churn']
for col in binary_cols:
    df[col] = df[col].map({'Yes':1, 'No':0, 'Female':1, 'Male':0})

In [126]:
df['Churn'].value_counts(normalize=True)

Churn
0    0.73463
1    0.26537
Name: proportion, dtype: float64

In [127]:
df.info()
df = df.astype(int)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7043 non-null   int64
 1   Partner                                7043 non-null   int64
 2   Dependents                             7043 non-null   int64
 3   tenure                                 7043 non-null   int64
 4   MultipleLines                          7043 non-null   int64
 5   OnlineSecurity                         7043 non-null   int64
 6   OnlineBackup                           7043 non-null   int64
 7   DeviceProtection                       7043 non-null   int64
 8   TechSupport                            7043 non-null   int64
 9   StreamingTV                            7043 non-null   int64
 10  StreamingMovies                        7043 non-null   int64
 11  PaperlessBilling                       7043 non-null   int64
 12  MonthlyCharges                         7043 non-null   float64
 13  TotalCharges                           7043 non-null   float64
 14  Churn                                  7043 non-null   int64
 15  NumServices                            7043 non-null   int64
 16  AvgMonthlyCharge                       7043 non-null   float64
 17  Contract_One year                      7043 non-null   bool
 18  Contract_Two year                      7043 non-null   bool
 19  PaymentMethod_Credit card (automatic)  7043 non-null   bool
 20  PaymentMethod_Electronic check         7043 non-null   bool
 21  PaymentMethod_Mailed check             7043 non-null   bool
 22  InternetService_Fiber optic            7043 non-null   bool
 23  InternetService_No                     7043 non-null   bool
dtypes: bool(7), float64(3), int64(14)
memory usage: 983.7 KB

In [128]:
df

,SeniorCitizen,Partner,Dependents,tenure,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,...,Churn,NumServices,AvgMonthlyCharge,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,InternetService_Fiber optic,InternetService_No
0,0,1,0,1,0,0,1,0,0,0,...,0,1,14,0,0,0,1,0,0,0
1,0,0,0,34,0,1,0,1,0,0,...,0,2,53,1,0,0,0,1,0,0
2,0,0,0,2,0,1,1,0,0,0,...,1,2,36,0,0,0,0,1,0,0
3,0,0,0,45,0,1,0,1,1,0,...,0,3,40,1,0,0,0,0,0,0
4,0,0,0,2,0,0,0,0,0,0,...,1,0,50,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,24,1,1,0,1,1,1,...,0,6,79,1,0,0,0,1,0,0
7039,0,1,1,72,1,0,1,1,0,1,...,0,5,100,1,0,1,0,0,1,0
7040,0,1,1,11,0,1,0,0,0,0,...,0,1,28,0,0,0,1,0,0,0
7041,1,1,0,4,1,0,0,0,0,0,...,1,1,61,0,0,0,0,1,1,0
7042,0,0,0,66,0,1,0,1,1,1,...,0,5,102,0,1,0,0,0,1,0

In [129]:
from sklearn.model_selection import train_test_split

# X = all features except Churn
X = df.drop('Churn', axis=1)
y = df['Churn']  # already 0/1

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [130]:
# Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [131]:
# Logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score
)

# Create model
lr = LogisticRegression(max_iter=1000)

# Train model
lr.fit(X_train, y_train)

# Make predictions
y_pred = lr.predict(X_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Accuracy
print(
    "Accuracy:",
    accuracy_score(y_test, y_pred)
)

Confusion Matrix:
[[938  98]
 [164 209]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.91      0.88      1036
           1       0.68      0.56      0.61       373

    accuracy                           0.81      1409
   macro avg       0.77      0.73      0.75      1409
weighted avg       0.81      0.81      0.81      1409

Accuracy: 0.8140525195173882

In [ ]:
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score
)

# Create model
dt = DecisionTreeClassifier(
    max_depth=12,
    random_state=42
)

# Train model
dt.fit(X_train, y_train)

# Make predictions
y_pred = dt.predict(X_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Accuracy
print(
    "Accuracy:",
    accuracy_score(y_test, y_pred)
)

Confusion Matrix:
[[866 170]
 [196 177]]

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.84      0.83      1036
           1       0.51      0.47      0.49       373

    accuracy                           0.74      1409
   macro avg       0.66      0.66      0.66      1409
weighted avg       0.73      0.74      0.74      1409

Accuracy: 0.7402413058907026

In [188]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
cm = confusion_matrix(y_test , y_pred)
print("confusion matrix")
print(cm)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print(f"accuracy_score {accuracy_score(y_test,y_pred)}")

confusion matrix
[[945  91]
 [194 179]]

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.91      0.87      1036
           1       0.66      0.48      0.56       373

    accuracy                           0.80      1409
   macro avg       0.75      0.70      0.71      1409
weighted avg       0.79      0.80      0.79      1409

accuracy_score 0.7977288857345636

In [199]:
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix

# Create model
xg = XGBClassifier(
    random_state=42
)

# Train model
xg.fit(X_train, y_train)

# Make predictions
xg_pred = xg.predict(X_test)

# Confusion Matrix
cm = confusion_matrix(y_test, xg_pred)

print("Confusion Matrix:")
print(cm)

print(f"classification matrix {classification_report (y_test,xg_pred)}")

Confusion Matrix:
[[929 107]
 [178 195]]
classification matrix               precision    recall  f1-score   support

           0       0.84      0.90      0.87      1036
           1       0.65      0.52      0.58       373

    accuracy                           0.80      1409
   macro avg       0.74      0.71      0.72      1409
weighted avg       0.79      0.80      0.79      1409

In [200]:
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score,
    roc_auc_score
)

# Probability for ROC-AUC
xg_prob = xg.predict_proba(X_test)[:, 1]

print("Confusion Matrix:")
print(confusion_matrix(y_test, xg_pred))

print("\nClassification Report:")
print(classification_report(y_test, xg_pred))

print(
    "Accuracy:",
    accuracy_score(y_test, xg_pred)
)

print(
    "ROC-AUC:",
    roc_auc_score(y_test, xg_prob)
)

Confusion Matrix:
[[929 107]
 [178 195]]

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1036
           1       0.65      0.52      0.58       373

    accuracy                           0.80      1409
   macro avg       0.74      0.71      0.72      1409
weighted avg       0.79      0.80      0.79      1409

Accuracy: 0.7977288857345636
ROC-AUC: 0.8389674143695591